spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 1800000
    #password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
